### ISSUE TITLE
Announce consolidation of OpenSSF and CII initiatives

### ISSUE THREAD

**Issue by kaywilliams** [ossf/gb-strategy-committee#8]
Consolidate current CCI and LF security initiatives under OpenSSF

**Comment by kaywilliams** [comment]
Who do we talk with in LF to plan consolidation of CII with OpenSSF?

**Comment by caniszczyk** [comment]
@david-a-wheeler is the best bet to start the conversation

This is a bit complicated as I believe you will follow this path:
1) identify the relevant CII efforts that you desire
2) propose them to the TAC for a vote
3) decide how to consolidate messaging

**Comment by kaywilliams** [comment]
I think we want to fully consolidate OpenSSF and CII. It may take some time, but that should be our direction.

**Comment by david-a-wheeler** [comment]
I intend to start by listing the working groups (along with explanations since their names are sometimes misleading) and listing the CII activities, and then proposing plausible matches along with other thoughts about transition.

I know there are several CII activities that aren't immediately visible, so we'll need to track that down, and I suspect there are cases where there's more than one plausible working group as a destination.

I think it would be easiest to start by drafting a Google doc, that way people can easily kibitz and make little improvements.

**Comment by dlorenc** [comment]
> 1. identify the relevant CII efforts that you desire
> 2. propose them to the TAC for a vote
> 3. decide how to consolidate messaging

@caniszczyk - are there any other stakeholders in the CII/LF that would need to agree/approve on any changes? Or is this all in the OSSF's court at this point?

**Comment by david-a-wheeler** [comment]
I created a proposed plan in the Google doc 
[Proposed Plan to Integrate CII into OpenSSF](https://docs.google.com/document/d/1fKoriYszCEYuNsj1v44LxfBmLEuMqjos21Yc_iEGB0w).

To create this proposal, I first extracted current declarations about the OpenSSF working groups’ scopes (which are still in flux); these are shown in the appendix. I then listed all ongoing CII activities (and some related ones). For each activity I propose how & where they could move into OpenSSF.

The proposed overall plan is to integrate existing CII activities into OpenSSF and eventually officially dissolve the CII. The CII was originally funded for 3 years; those 3 years have ended, and the LF has been working to keep some CII activities going where they made sense. Now that the OpenSSF exists, it makes sense to transition them to the OpenSSF if the OpenSSF wants them.The goal is to have smooth transitions where the OpenSSF wants to pick up the work.

I believe these decisions are entirely the OpenSSF’s to make. I think are some confusions because I think there are two different groups named the "SC Steering Committee" (as I discuss in detail in my proposal).

Again, this is merely a proposal, with the hope that it starts a conversation & provides some useful background. It is the OpenSSF that decides what the OpenSSF will do :-).

**Comment by david-a-wheeler** [comment]
Here's quick summary of the existing CII (& related) Activities, along with my proposed home in OpenSSF for them:

* EdX “Fundamentals” course → Best Practices (incl. Education) WG . This isn't a CII activity, but it's related. See the [Doodle poll](https://doodle.com/poll/wkwgpzmbhmmgdy3f)
* CII Best Practices badge → Security Threat (incl. Metrics) WG, alternate Best Practices (incl. Education) WG
  - This is complicated, because it's relevant to two WGs! Recommend changes be coordinated/vetted by both WGs
* CII Census (of critical projects) & CII Survey (of developers) → Securing Critical Projects WG
* Funding for some specific work on OpenSSH/OpenBSD/Linux kernel → Securing Critical Projects WG

Again: This is just a proposal. It is the OpenSSF, not me, who makes these decisions.

**Comment by kaywilliams** [comment]
Thanks David, this proposal seems like a good starting point.

I think our next steps are as follows:

@david-a-wheeler to work with the respective WG's to create GitHub issues, something like the following:

- Proposal to adopt EdX fundamentals course
- Proposal to adopt CII Best Practices badge initiative
- Proposal to adopt CII Census and CII Survey initiatives
- Proposal to adopt LF sponsored security work for OpenSSH/OpenBSD/Linux kernel

Once these issues are created, it would be great to add them to the rollup issue I recently created for TAC discussion.

[Review WG proposals for adopting LF and CII initiatives](https://github.com/ossf/tac/issues/25)

I'm open to better ways to handle this, if others have ideas.

**Comment by dlorenc** [comment]
Opened https://github.com/ossf/wg-securing-critical-projects/issues/14 to track the Census part.

**Comment by david-a-wheeler** [comment]
@kaywilliams - I will create these issues once the TAC meeting today is complete, assuming the TAC doesn't override it.

**Comment by LindsayLF** [comment]
@david-a-wheeler @kaywilliams - Can you provide 3-5 bullet points about the merge for the press release? Thank you!

**Comment by david-a-wheeler** [comment]
@LindsayLF - will do via email.

**Comment by LindsayLF** [comment]
@david-a-wheeler, Thank you!!

**Comment by kaywilliams** [comment]
@LindsayLF, @david-a-wheeler - how about this for the press release:
----

Existing projects in the Core Infrastructure Initiative (CII) are now being consolidated into the newer OpenSSF. Specific projects include the following:
•	The CII Census (a quantitative analysis to identify critical OSS projects) and CII Survey (a quantitative survey of OSS developers). These two efforts will continue to be implemented by the Laboratory for Innovation Science at Harvard (LISH).
•	The CII Best Practices Badge Program.
This consolidation is being done in a thoughtful way to prevent disruption. Once complete the CII is expected to be officially dissolved, with the OpenSSF taking over as the hub for collaboration to secure the open source ecosystem.

**Comment by david-a-wheeler** [comment]
@kaywilliams - looks good to me!

**Comment by LindsayLF** [comment]
@kaywilliams - Looks good, please review the press release draft for alignment to this content.  Thank you!

**Comment by kaywilliams** [comment]
Looks good. Closing this issue.
